import { getDatabase } from '../config/database';
import { analyses, analysisResults, reports } from '../config/schema';
import { eq } from 'drizzle-orm';
import { logger } from '../config/logger';
import { marked } from 'marked';
import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

export class ReportService {
  async generateReport(
    analysisId: number,
    format: 'json' | 'markdown' | 'pdf'
  ): Promise<{ buffer: Buffer; fileName: string }> {
    try {
      const db = getDatabase();

      // Fetch analysis and results
      const [analysis] = await db
        .select()
        .from(analyses)
        .where(eq(analyses.id, analysisId));

      if (!analysis) {
        throw new Error('Analysis not found');
      }

      if (analysis.status !== 'completed') {
        throw new Error('Analysis not completed');
      }

      const results = await db
        .select()
        .from(analysisResults)
        .where(eq(analysisResults.analysisId, analysisId));

      const report = this.buildReport(analysis, results);
      const timestamp = new Date().toISOString().split('T')[0];
      const fileName = `${analysis.projectName}-analysis-${timestamp}`;

      let buffer: Buffer;

      switch (format) {
        case 'json':
          buffer = Buffer.from(JSON.stringify(report, null, 2), 'utf-8');
          break;
        case 'markdown':
          buffer = Buffer.from(this.generateMarkdown(report), 'utf-8');
          break;
        case 'pdf':
          buffer = await this.generatePDF(report);
          break;
        default:
          throw new Error('Unsupported format');
      }

      // Store report metadata
      await db.insert(reports).values({
        analysisId,
        format,
        fileName: `${fileName}.${format === 'pdf' ? 'pdf' : 'txt'}`,
        fileSize: buffer.length,
        summary: report.summary,
      });

      return { buffer, fileName: `${fileName}.${format === 'pdf' ? 'pdf' : 'txt'}` };
    } catch (error) {
      logger.error('Report generation failed', error);
      throw error;
    }
  }

  private buildReport(analysis: any, results: any[]) {
    const dimensions = results.reduce(
      (acc, r) => {
        acc[r.dimension] = r.details;
        return acc;
      },
      {} as Record<string, any>
    );

    const overallScore = Math.round(
      results.reduce((sum, r) => sum + r.score, 0) / results.length
    );

    const allIssues = results.flatMap((r) =>
      r.details.issues.map((i: any) => ({ ...i, dimension: r.dimension }))
    );

    const criticalIssues = allIssues.filter((i) => i.severity === 'critical');
    const highIssues = allIssues.filter((i) => i.severity === 'high');

    return {
      projectName: analysis.projectName,
      description: analysis.description,
      analyzedAt: analysis.completedAt,
      overallScore,
      dimensions,
      summary: {
        totalIssues: allIssues.length,
        criticalIssues: criticalIssues.length,
        highIssues: highIssues.length,
        topIssues: allIssues.slice(0, 5),
        topSuggestions: this.aggregateSuggestions(results).slice(0, 5),
      },
    };
  }

  private generateMarkdown(report: any): string {
    let markdown = `# Code Analysis Report

**Project:** ${report.projectName}
**Analyzed:** ${new Date(report.analyzedAt).toLocaleString()}
**Overall Score:** ${report.overallScore}/100

## Summary

- Total Issues: ${report.summary.totalIssues}
- Critical Issues: ${report.summary.criticalIssues}
- High Priority Issues: ${report.summary.highIssues}

## Analysis Dimensions

`;

    Object.entries(report.dimensions).forEach(([dimension, data]: [string, any]) => {
      markdown += `### ${dimension}
Score: **${data.score}/100**

#### Issues (${data.issues.length})
`;
      data.issues.slice(0, 5).forEach((issue: any) => {
        markdown += `- **[${issue.severity.toUpperCase()}]** ${issue.message}\n`;
      });

      markdown += `\n#### Suggestions\n`;
      data.suggestions.slice(0, 3).forEach((suggestion: string) => {
        markdown += `- ${suggestion}\n`;
      });

      markdown += '\n';
    });

    markdown += `## Recommendations

${report.summary.topSuggestions.map((s: string) => `- ${s}`).join('\n')}

---
*Report generated by AI Code Analyzer*
`;

    return markdown;
  }

  private async generatePDF(report: any): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({ margin: 50 });

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Title
      doc.fontSize(24).font('Helvetica-Bold').text('Code Analysis Report', { align: 'center' });
      doc.moveDown(0.5);

      // Metadata
      doc.fontSize(12).font('Helvetica');
      doc.text(`Project: ${report.projectName}`);
      doc.text(`Analyzed: ${new Date(report.analyzedAt).toLocaleString()}`);
      doc.moveDown(1);

      // Overall Score
      doc.fontSize(18).font('Helvetica-Bold').text(`Overall Score: ${report.overallScore}/100`);
      doc.moveDown(1);

      // Summary
      doc.fontSize(14).font('Helvetica-Bold').text('Summary');
      doc.fontSize(11).font('Helvetica');
      doc.text(`Total Issues: ${report.summary.totalIssues}`);
      doc.text(`Critical Issues: ${report.summary.criticalIssues}`);
      doc.text(`High Priority Issues: ${report.summary.highIssues}`);
      doc.moveDown(1);

      // Dimensions
      Object.entries(report.dimensions).forEach(([dimension, data]: [string, any]) => {
        doc.fontSize(14).font('Helvetica-Bold').text(dimension);
        doc.fontSize(11).font('Helvetica');
        doc.text(`Score: ${data.score}/100`);

        doc.fontSize(10).text('Issues:');
        data.issues.slice(0, 3).forEach((issue: any) => {
          doc.text(`  • [${issue.severity.toUpperCase()}] ${issue.message}`, {
            width: 400,
          });
        });

        doc.moveDown(0.5);
      });

      doc.end();
    });
  }

  private aggregateSuggestions(results: any[]): string[] {
    const suggestions = new Map<string, number>();

    results.forEach((r) => {
      r.details.suggestions.forEach((suggestion: string) => {
        suggestions.set(suggestion, (suggestions.get(suggestion) || 0) + 1);
      });
    });

    return Array.from(suggestions.entries())
      .sort((a, b) => b[1] - a[1])
      .map(([suggestion]) => suggestion);
  }
}
